apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: payment-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4007
          env:
            - name: PORT
              value: "4007"
            - name: MONGO_URI
              value: "mongodb://mongodb:27017/payment_db"
            - name: JWT_SECRET
              value: "secret"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  type: ClusterIP
  selector:
    app: payment-service
  ports:
    - protocol: TCP
      port: 4007
      targetPort: 4007
