apiVersion: apps/v1
kind: Deployment
metadata:
  name: telemedicine-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telemedicine-service
  template:
    metadata:
      labels:
        app: telemedicine-service
    spec:
      containers:
        - name: telemedicine-service
          image: telemedicine-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4008
          env:
            - name: PORT
              value: "4008"
            - name: MONGO_URI
              value: "mongodb://mongodb:27017/telemedicine_db"
            - name: JWT_SECRET
              value: "secret"
---
apiVersion: v1
kind: Service
metadata:
  name: telemedicine-service
spec:
  type: ClusterIP
  selector:
    app: telemedicine-service
  ports:
    - protocol: TCP
      port: 4008
      targetPort: 4008
